version: '3.7'
services:
    server:
        build: ./server
        volumes: 
            - ./server:/code
        ports:
            - "5000:5000"
        depends_on: 
            - redis
    redis:
        image: redis